A new chinese text example on the version 0.8.0
jina-ai/examples pull request #322
Opened 2020-12-22 02:21 UTC by ultimatedaotu

A new chinese text example based on webwq-search example on the version of jina==0.8.0. Because there are some problems at query-flow, I need your kind help.

2020-12-28 15:52 UTC, nan-wang requested changes
Thanks for your work. However, this is a misusage of PRs. I've fixed your problems and the main issue is due to the misunderstanding of document recursive structures. You might found more detail at our last EAH. The recording is at https://youtu.be/chmVNrRdiKI?t=2204

2020-12-28 15:52 UTC, nan-wang commented on zh/textsearch/flow-query.yml
> +#    timeout_ready: 60000
```suggestion
  ranker:
    uses: pods/ranker/ranker.yml

  doc_indexer:
    uses: pods/doc_indexer/doc_indexer.yml
```

2020-12-28 15:52 UTC, nan-wang commented on zh/textsearch/pods/chunk_indexer/chunk_indexer.yml
> +  workspace: $TMP_WORKSPACE
```suggestion
  workspace: $TMP_WORKSPACE
requests:
  on:
    SearchRequest:
      - !VectorSearchDriver
        with:
          executor: vecidx_index
          traversal_paths: ['c']
      - !ExcludeQL
        with:
          fields:
            - embedding
      - !KVSearchDriver
        with:
          executor: chunk_index
          traversal_paths: ['cm']
    IndexRequest:
      - !VectorIndexDriver
        with:
          executor: vecidx_index
          traversal_paths: ['c']
      - !ExcludeQL
        with:
          fields:
            - embedding
      - !KVIndexDriver
        with:
          executor: chunk_index
          traversal_paths: ['c']
    ControlRequest:
      - !ControlReqDriver {}
```

2020-12-28 15:52 UTC, nan-wang commented on zh/textsearch/pods/doc_indexer/doc_indexer.yml
> +  workspace: $TMP_WORKSPACE
```suggestion
  workspace: $TMP_WORKSPACE
  name: doc_index
requests:
  on:
    ControlRequest:
      - !ControlReqDriver {}
    SearchRequest:
      - !KVSearchDriver
        with:
          traversal_paths: ['m']
    IndexRequest:
      - !KVIndexDriver
        with:
          traversal_paths: ['r']
```

2020-12-28 15:52 UTC, nan-wang commented on zh/textsearch/pods/encoder/encoder2.yml
> +          method: encode
```suggestion
          traversal_paths: ['c']
```

2020-12-28 15:52 UTC, nan-wang commented on zh/textsearch/pods/ranker/ranker.yml
> +          method: score
```suggestion
                    traversal_paths: ['c']
      - !ExcludeQL
        with:
          fields:
            - embedding
            - chunks
          traversal_paths: ['r', 'c']
      - !SliceQL
        with:
          traversal_paths: ['m']
          start: 0
          end: 10
```

2020-12-28 15:52 UTC, nan-wang commented on zh/textsearch/pods/ranker/ranker.yml
> +!BM25Ranker
For `0.8.0`, you will add one line at https://github.com/jina-ai/jina-hub/blob/master/rankers/BM25Ranker/__init__.py#L19

```
required_keys = {'text', 'length'}
```

2021-01-09 12:47 UTC, alexcg1 commented
Thanks for your PR @ultimatedaotu ! We're currently restructuring our examples repo, so it might be more useful to post this on our own personal repo and we can link it in our upcoming "Community Examples" section

2021-03-04 11:30 UTC, nan-wang commented
@ultimatedaotu We've created an example in Chinese for the `1.0` and please check it out.

2021-03-04 11:30 UTC, closed without merging