feat: draft clip encoder
jina-ai/examples pull request #401
Opened 2021-02-18 14:52 UTC by davidbp

2021-02-18 14:58 UTC, davidbp commented
Need to add test for batch of images and batch of text

2021-02-18 15:02 UTC, bwanglzu commented
and don't forget to ignore notebook from the pull request

2021-02-18 15:06 UTC, JoanFM commented
It looks good. Few comments:

```
These Encoders should be `adapters` from `CLIP` hub models, so we do not need to hardcode the model name (the same way our `TransformerTorchEncoder` accepst hub names from hugging face hub.

Try to make use of the `TorchDevice` construction to move the model to `cpu` or `gpu` according to the `on_gpu` flag.
```

2021-02-19 07:50 UTC, JoanFM requested changes

2021-02-19 07:50 UTC, JoanFM commented on cross-modal-search/ClipImageEncoder/CLIPImageEncoder/__init__.py
> +class CLIPImageEncoder(BaseTorchEncoder, TorchDevice):
The mixin class should come before the `parent class`

2021-02-19 07:50 UTC, JoanFM commented on cross-modal-search/ClipImageEncoder/CLIPImageEncoder/__init__.py
> +        model, preprocess = clip.load('ViT-B/32', device)
use `self.device` which actually detects

2021-02-19 07:50 UTC, JoanFM commented on cross-modal-search/ClipImageEncoder/CLIPImageEncoder/__init__.py
> +        model, preprocess = clip.load('ViT-B/32', device)
add a `model_name` parameter so that it can choose which CLIP model can be used. ( we can check if the input is part of the `clip.available_models`

2021-02-19 07:50 UTC, JoanFM commented on cross-modal-search/ClipImageEncoder/CLIPImageEncoder/__init__.py
> +        model, preprocess = clip.load('ViT-B/32', device)
CLIP now has `ViT-B/32` and `RN50` so someone may want to try different options

2021-02-19 07:50 UTC, JoanFM commented on cross-modal-search/ClipImageEncoder/CLIPTextEncoder/__init__.py
> +class CLIPTextEncoder(BaseTorchEncoder, TorchDevice):
same as in the image version

2021-02-22 12:41 UTC, JoanFM requested changes

2021-02-22 12:41 UTC, JoanFM commented on cross-modal-search/ClipImageEncoder/CLIPTextEncoder/tests/test_clipitextencoder.py
>      device='cpu'
no need for device here

2021-02-22 12:41 UTC, JoanFM commented on cross-modal-search/ClipImageEncoder/CLIPImageEncoder/tests/test_clipimageencoder.py
> +    device='cpu'
also here

2021-02-23 10:39 UTC, JoanFM requested changes

2021-02-23 10:39 UTC, JoanFM commented on cross-modal-search/ClipImageEncoder/CLIPImageEncoder/__init__.py
> +            return self.model.encode_image(input_torchtensor)
we need the result to be in CPU, this needs to be taken care for

2021-02-23 10:39 UTC, JoanFM commented on cross-modal-search/ClipImageEncoder/CLIPTextEncoder/__init__.py
> +            return self.model.encode_text(input_torchtensor)
same here

2021-02-23 11:39 UTC, JoanFM reviewed
What needs to be done in my opinion is to remove the `encoding_with_original_clip.py` and just get the `.npy` artifacts in the repo to be accessible by tests

2021-02-23 11:40 UTC, JoanFM requested changes

2021-02-23 11:40 UTC, JoanFM commented on cross-modal-search/ClipImageEncoder/CLIPTextEncoder/tests/test_clipitextencoder.py
> +    models = ['ViT-B/32', 'RN50']
test that loading a different model raises the expected exception

2021-02-23 14:19 UTC, JoanFM reviewed
Close these changes,u should work in the `jina-hub` repo not in the `examples` one

2021-02-23 20:52 UTC, closed without merging