feat: clean up vse cross modal
jina-ai/examples pull request #409
Opened 2021-03-01 09:28 UTC by bwanglzu

The objective of this ticket:

- [ ] Clean up the current cross modal a bit.
- [ ] Add evaluate pod into the flow.

Follow up task:
Add CLIP integration & result comparison.

2021-03-03 07:25 UTC, JoanFM commented on cross-modal-search/evaluate.py
> +def input_index_data(num_docs=None, batch_size=8, dataset_type='f30k'):
we could maybe move all these generators into `dataset.py`?

2021-03-03 07:25 UTC, JoanFM commented on cross-modal-search/flow-index.yml
> +    uses_internal: $JINA_TEXT_ENCODER_INTERNAL
I comment it here, but is not here, change the `_merge` in line 40 for `_pass`

2021-03-03 08:32 UTC, JoanFM commented on cross-modal-search/evaluate.py
> +    num_of_matches += len(resp.search.docs)
as a sanity check, can u sum the num of matches naively from the number of Evaluations u compute and see if it matches

2021-03-03 09:30 UTC, JoanFM commented on cross-modal-search/flow-index.yml
> +    uses_internal: $JINA_TEXT_ENCODER_INTERNAL
my bad, better to keep it as `_merge_root`

2021-03-04 13:53 UTC, JoanFM requested changes

2021-03-04 13:53 UTC, JoanFM commented on cross-modal-search/README.md
> +Both of the models has been trained that encodes pair of `text` and `images` into a common embedding space.
both of the models have been trained to encode

2021-03-04 14:19 UTC, JoanFM commented on cross-modal-search/README.md
> +Both of the models have been trained that encodes pair of `text` and `images` into a common embedding space.
have been trained 'to' encode

2021-03-05 05:00 UTC, bwanglzu commented
waiting for `1.0.8` release

2021-03-05 06:16 UTC, JoanFM commented
> waiting for `1.0.8` release

we need to find a deterministic hashing where we can provide the  seed or something

2021-03-05 08:06 UTC, JoanFM commented on cross-modal-search/dataset.py
> +            encoded = base64.b64encode(image)
does this depend on thr PYTHONSEED as well?

2021-03-05 08:08 UTC, bwanglzu commented
@JoanFM no, i forgot to remove this

2021-03-08 11:18 UTC, JoanFM approved these changes

2021-03-08 11:18 UTC, merged