fix: update object search
jina-ai/examples pull request #426
Opened 2021-03-12 00:39 UTC by Yongxuanzhang

2021-03-12 07:37 UTC, JoanFM requested changes

2021-03-12 07:37 UTC, JoanFM commented on object-search/app.py
> +@click.option('--task', '-task', "-t", type=click.Choice(['index', 'query'], case_sensitive=False))
please keep single quote

2021-03-12 13:48 UTC, Yongxuanzhang commented on object-search/app.py
> +@click.option('--task', '-task', "-t", type=click.Choice(['index', 'query'], case_sensitive=False))
Sure, sorry my bad.

2021-03-12 14:39 UTC, JoanFM submitted a review, later dismissed
there are a lot of parameters in the yaml files that correspond to old jina versions.

`uses_reducing` is not used anymore, as well as separatrd workspace

2021-03-12 15:32 UTC, Yongxuanzhang commented
> there are a lot of parameters in the yaml files that correspond to old jina versions.
> 
> `uses_reducing` is not used anymore, as well as separatrd workspace

Do we have the list of deprecated params?

2021-03-12 15:37 UTC, JoanFM commented
> > there are a lot of parameters in the yaml files that correspond to old jina versions.
> > `uses_reducing` is not used anymore, as well as separatrd workspace
> 
> Do we have the list of deprecated params?

Unfortunatey not, I can help u later

2021-03-12 20:02 UTC, Yongxuanzhang commented
> > > there are a lot of parameters in the yaml files that correspond to old jina versions.
> > > `uses_reducing` is not used anymore, as well as separatrd workspace
> > 
> > 
> > Do we have the list of deprecated params?
> 
> Unfortunatey not, I can help u later

The YAML has been updated with the help of @JoanFM 👍

2021-03-15 07:40 UTC, nan-wang approved these changes
LGTM👍

2021-03-15 18:35 UTC, merged