fix: multi modal eg using CRUD REST
jina-ai/examples pull request #467
Opened 2021-04-22 10:44 UTC by rutujasurve94

update Jina to 1.1.0
modify flow yamls to enable REST API
add index_rest that indexes docs using the /index REST API
add index_rest to click options
change README to point towards /search (NOT /api/search)

2021-04-28 07:47 UTC, cristianmtr commented on multimodal-search-tirg/app.py
> +        print(f'Indexing {data_path}')
remove print statements

2021-04-28 07:48 UTC, cristianmtr requested changes
small thing

2021-04-28 11:40 UTC, rutujasurve94 commented on multimodal-search-tirg/app.py
> +        print(f'Indexing {data_path}')
done

2021-04-29 08:59 UTC, cristianmtr commented on multimodal-search-tirg/README.MD
> +```sh
Is this relevant for the multimodal search? This curl is using text

2021-05-03 16:10 UTC, nan-wang commented
This PR needs further improvement and we are working on 1.2 anyway.

2021-05-03 16:10 UTC, closed without merging