fix: update CRUD for fashion example
jina-ai/examples pull request #469
Opened 2021-04-22 13:30 UTC by rutujasurve94

update Jina to 1.1.0

modify flow yamls to enable REST API

add index_rest that indexes docs using the /index REST API

add index_rest to click options

change README to point towards /search (NOT /api/search)

2021-04-27 08:17 UTC, cristianmtr commented on fashion-example-query/app.py
> +        print(f'#### {len(data_json["data"])}')
remove print

2021-04-27 08:17 UTC, cristianmtr commented on fashion-example-query/app.py
> +    print(f'### task = {task}')
remove print

2021-04-27 08:17 UTC, cristianmtr submitted a review, later dismissed

2021-04-27 08:17 UTC, cristianmtr commented
Link it to the main ticket, if you haven't

2021-04-28 07:49 UTC, cristianmtr commented on fashion-example-query/app.py
> +        print(f'Indexing {data_path}')
remove print

2021-04-28 07:49 UTC, cristianmtr requested changes
remove print

2021-04-28 11:42 UTC, rutujasurve94 commented on fashion-example-query/app.py
> +        print(f'Indexing {data_path}')
done

2021-05-03 16:09 UTC, nan-wang commented
This PR needs further improvement and we are working on `1.2` anyway.

2021-05-03 16:09 UTC, closed without merging