fix: pokedex-bit using CRUD REST
jina-ai/examples pull request #473
Opened 2021-04-23 07:31 UTC by rutujasurve94

update Jina to 1.1.0

modify flow yamls to enable REST API

add index_rest that indexes docs using the /index REST API

add index_rest to click options

change README to point towards /search (NOT /api/search)

2021-04-24 11:31 UTC, nan-wang requested changes

2021-04-24 11:31 UTC, nan-wang commented on pokedex-with-bit/app.py
> +from jina.clients.sugary_io import _input_lines
clean up

2021-04-27 08:18 UTC, cristianmtr commented on pokedex-with-bit/app.py
> +        print(f'#### {len(data_json["data"])}')
remove print

2021-04-27 08:18 UTC, cristianmtr commented on pokedex-with-bit/app.py
> +    print(f'### task = {task}')
remove print

2021-04-27 08:18 UTC, cristianmtr approved these changes
Link it to the main ticket, if you haven't

2021-04-28 07:19 UTC, cristianmtr approved these changes

2021-04-28 07:48 UTC, cristianmtr submitted a review, later dismissed

2021-04-29 01:12 UTC, nan-wang requested changes

2021-04-29 01:12 UTC, nan-wang commented on pokedex-with-bit/README.md
> +````
Is this part valid?

2021-04-29 01:12 UTC, nan-wang commented on pokedex-with-bit/app.py
> +    config(task)
This leads to the error
```suggestion
    config(task)
```

2021-04-29 01:12 UTC, nan-wang commented on pokedex-with-bit/app.py
> +        config(task)
The same here
```suggestion
        config(task)
```

2021-04-29 01:12 UTC, nan-wang commented on pokedex-with-bit/app.py
>  from jina.flow import Flow
```suggestion
```

2021-04-29 01:12 UTC, nan-wang commented on pokedex-with-bit/app.py
> +from jina import Document
```suggestion
from jina import Document, Flow
```

2021-04-29 07:13 UTC, rutujasurve94 commented on pokedex-with-bit/app.py
> +        config(task)
Removed code.

2021-04-29 07:13 UTC, rutujasurve94 commented on pokedex-with-bit/app.py
> +    config(task)
Removed code

2021-04-29 07:14 UTC, rutujasurve94 commented on pokedex-with-bit/app.py
> +from jina import Document
Done

2021-04-29 07:14 UTC, rutujasurve94 commented on pokedex-with-bit/README.md
> +````
Removing the `curl` to avoid ambiguity.

2021-06-04 15:20 UTC, closed without merging