Object detection example rework
jina-ai/examples pull request #511
Opened 2021-04-29 10:52 UTC by aga11313

2021-04-29 13:45 UTC, FionnD requested changes
This is still in progress. I can't get the code running but I'll open an PR to see if someone else can. I can come back and review it once that issue is fixde.

2021-04-30 11:39 UTC, aga11313 commented on object-search/README.md
> +2. Identify the cropped sub images and their labels.
Okay, let me think about this some more

2021-04-30 13:11 UTC, FionnD commented
Reviewing this is blocked by https://github.com/jina-ai/examples/issues/519

2021-05-06 14:34 UTC, cristianmtr commented
@FionnD the example works for me now.

I cannot merge with `master` since there are too many changes in the README, and I'm not up to speed with what is the current vision. Should I just replace the changes in `master` with the ones in this PR?

2021-05-06 14:45 UTC, FionnD commented
Thanks @cristianmtr 

I don't quite understand what you mean, should you just move the app.py changes to another PR is it?

2021-05-06 14:48 UTC, cristianmtr commented
The PR is showing conflicting changes that cannot be automatically resolved in merging:

![image](https://user-images.githubusercontent.com/8330330/117318623-e1af1600-ae8a-11eb-9845-67a942bc3ea7.png)

I tried to rebase. The app.py merges fine, but the README has too many changes. And I'm not sure which is the way to go

2021-05-06 15:44 UTC, cristianmtr commented
I reverted my push to this PR. My bad, I thought this PR was for reworking the code itself too

2021-05-15 15:32 UTC, nan-wang commented
resolved the conflicts

2021-05-15 15:41 UTC, merged