fix pip numbers leakage
jina-ai/examples pull request #632
Opened 2021-06-01 12:36 UTC by alexcg1

Fixes https://github.com/jina-ai/internal-tasks/issues/86

TL;DR: anything installed from requirements.txt in examples repo is not tracked by pypi, so we can't get those numbers. If it's our CI doing that, we DON'T want those numbers. But if it's our users, we DO want those numbers. This PR creates a separate requirements.txt in each example's `test/` directory, and tells our CI to install from that. It reverts `./requirements.txt` to installing from pypi, which is what real users would do.

- test: separate reqs for users and ci. users install direct
- test: set ci to install requirements.txt from test dir

2021-06-01 12:39 UTC, alexcg1 commented
Thank god for vim's automation via `.`. That saved me a lot of work!

2021-06-03 02:46 UTC, nan-wang requested changes
We need to fix the version

2021-06-03 02:46 UTC, nan-wang commented on advanced-vector-search/requirements.txt
> +jina[hub, http]
```suggestion
jina[hub, http]==1.2.0
```

2021-06-04 08:39 UTC, alexcg1 commented on advanced-vector-search/requirements.txt
> +jina[hub, http]
Fixed for all

2021-06-06 15:27 UTC, nan-wang approved these changes
LGTM👍

2021-06-06 15:29 UTC, merged